/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package smbs;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;

/**
 *
 * @author sriram
 */
public class Billing extends javax.swing.JFrame {
    
    private Connection con;
    private Statement st;
    private PreparedStatement pst;
    private ResultSet rs;
    String pro_namee,pro_detaill;
    int pro_codee,stockk,min_stockk;
    double pricee;
    String cus_name,mob_num;
    String cus_name1;
    int cuscodee,cusquann,cuscodee1,cusquann1;
    double tot=0,tot1=0;
    double tot_cus=0,tot_cus1=0;
    int cnt=1;
    double tocus;

    /**
     * Creates new form Billing
     */
    public Billing() {
        try
        {
          Class.forName("com.mysql.jdbc.Driver");
          con = DriverManager.getConnection("jdbc:mysql://localhost:3306/Super?zeroDateTimeBehavior=convertToNull","root","");
          st = con.createStatement();
        }
        catch(Exception ex){
            System.out.println("Error : "+ex);
        }
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jFrame1 = new javax.swing.JFrame();
        jLabel4 = new javax.swing.JLabel();
        getcode = new javax.swing.JTextField();
        codebill = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        cusquan = new javax.swing.JTextField();
        prcode = new javax.swing.JLabel();
        prcode1 = new javax.swing.JLabel();
        prcode2 = new javax.swing.JLabel();
        backhome = new javax.swing.JButton();
        jFrame2 = new javax.swing.JFrame();
        jLabel7 = new javax.swing.JLabel();
        getcode1 = new javax.swing.JTextField();
        codebill1 = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        cusquan1 = new javax.swing.JTextField();
        prcode3 = new javax.swing.JLabel();
        prcode4 = new javax.swing.JLabel();
        prcode5 = new javax.swing.JLabel();
        backhome1 = new javax.swing.JButton();
        jFrame3 = new javax.swing.JFrame();
        jLabel6 = new javax.swing.JLabel();
        totbiling = new javax.swing.JLabel();
        home = new javax.swing.JButton();
        newcus = new javax.swing.JRadioButton();
        exscus = new javax.swing.JRadioButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        cusnme = new javax.swing.JTextField();
        cusnum = new javax.swing.JTextField();
        addcus = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        cusnme1 = new javax.swing.JTextField();
        seacus = new javax.swing.JButton();

        jFrame1.setSize(new java.awt.Dimension(350, 350));

        jLabel4.setText("Product Code :");

        getcode.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                getcodeActionPerformed(evt);
            }
        });

        codebill.setText("Bill");
        codebill.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                codebillActionPerformed(evt);
            }
        });

        jLabel5.setText("Quantity");

        backhome.setText("Exit");
        backhome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backhomeActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jFrame1Layout = new javax.swing.GroupLayout(jFrame1.getContentPane());
        jFrame1.getContentPane().setLayout(jFrame1Layout);
        jFrame1Layout.setHorizontalGroup(
            jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jFrame1Layout.createSequentialGroup()
                .addGroup(jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jFrame1Layout.createSequentialGroup()
                        .addGap(63, 63, 63)
                        .addComponent(jLabel4))
                    .addGroup(jFrame1Layout.createSequentialGroup()
                        .addGap(77, 77, 77)
                        .addComponent(jLabel5)))
                .addGap(49, 49, 49)
                .addGroup(jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(getcode)
                    .addComponent(cusquan, javax.swing.GroupLayout.DEFAULT_SIZE, 111, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jFrame1Layout.createSequentialGroup()
                .addGap(0, 75, Short.MAX_VALUE)
                .addGroup(jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jFrame1Layout.createSequentialGroup()
                        .addComponent(prcode1, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(prcode2, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jFrame1Layout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addComponent(codebill)))
                .addGap(29, 29, 29)
                .addGroup(jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(prcode, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(backhome))
                .addGap(75, 75, 75))
        );
        jFrame1Layout.setVerticalGroup(
            jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jFrame1Layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addGroup(jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(getcode, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25)
                .addGroup(jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(cusquan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(codebill)
                    .addComponent(backhome))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 45, Short.MAX_VALUE)
                .addGroup(jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(prcode, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(prcode2, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(prcode1, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(65, 65, 65))
        );

        jFrame2.setSize(new java.awt.Dimension(350, 350));

        jLabel7.setText("Product Code :");

        getcode1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                getcode1ActionPerformed(evt);
            }
        });

        codebill1.setText("Bill");
        codebill1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                codebill1ActionPerformed(evt);
            }
        });

        jLabel8.setText("Quantity");

        cusquan1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cusquan1ActionPerformed(evt);
            }
        });

        backhome1.setText("Exit");
        backhome1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backhome1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jFrame2Layout = new javax.swing.GroupLayout(jFrame2.getContentPane());
        jFrame2.getContentPane().setLayout(jFrame2Layout);
        jFrame2Layout.setHorizontalGroup(
            jFrame2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jFrame2Layout.createSequentialGroup()
                .addGroup(jFrame2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jFrame2Layout.createSequentialGroup()
                        .addGap(63, 63, 63)
                        .addComponent(jLabel7))
                    .addGroup(jFrame2Layout.createSequentialGroup()
                        .addGap(77, 77, 77)
                        .addComponent(jLabel8)))
                .addGap(49, 49, 49)
                .addGroup(jFrame2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(getcode1)
                    .addComponent(cusquan1, javax.swing.GroupLayout.DEFAULT_SIZE, 111, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jFrame2Layout.createSequentialGroup()
                .addGap(0, 75, Short.MAX_VALUE)
                .addGroup(jFrame2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jFrame2Layout.createSequentialGroup()
                        .addComponent(prcode3, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(prcode5, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jFrame2Layout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addComponent(codebill1)))
                .addGap(29, 29, 29)
                .addGroup(jFrame2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(prcode4, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(backhome1))
                .addGap(75, 75, 75))
        );
        jFrame2Layout.setVerticalGroup(
            jFrame2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jFrame2Layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addGroup(jFrame2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(getcode1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25)
                .addGroup(jFrame2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(cusquan1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jFrame2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(codebill1)
                    .addComponent(backhome1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 56, Short.MAX_VALUE)
                .addGroup(jFrame2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(prcode4, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(prcode5, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(prcode3, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(65, 65, 65))
        );

        jFrame3.setSize(new java.awt.Dimension(350, 350));

        jLabel6.setText("Total Bill Amount");

        home.setText("Ok");
        home.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                homeActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jFrame3Layout = new javax.swing.GroupLayout(jFrame3.getContentPane());
        jFrame3.getContentPane().setLayout(jFrame3Layout);
        jFrame3Layout.setHorizontalGroup(
            jFrame3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jFrame3Layout.createSequentialGroup()
                .addContainerGap(149, Short.MAX_VALUE)
                .addGroup(jFrame3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jFrame3Layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addGap(142, 142, 142))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jFrame3Layout.createSequentialGroup()
                        .addGroup(jFrame3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(home)
                            .addComponent(totbiling, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(107, 107, 107))))
        );
        jFrame3Layout.setVerticalGroup(
            jFrame3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jFrame3Layout.createSequentialGroup()
                .addGap(60, 60, 60)
                .addComponent(jLabel6)
                .addGap(42, 42, 42)
                .addComponent(totbiling, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(55, 55, 55)
                .addComponent(home)
                .addContainerGap(73, Short.MAX_VALUE))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        newcus.setText("New Customer");

        exscus.setText("Existing Customer");

        jLabel1.setText("Customer name :");

        jLabel2.setText("Customer number :");

        cusnme.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cusnmeActionPerformed(evt);
            }
        });

        cusnum.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cusnumActionPerformed(evt);
            }
        });

        addcus.setText("Add");
        addcus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addcusActionPerformed(evt);
            }
        });

        jLabel3.setText("Customer name :");

        cusnme1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cusnme1ActionPerformed(evt);
            }
        });

        seacus.setText("Search");
        seacus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                seacusActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel1))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(cusnum, javax.swing.GroupLayout.DEFAULT_SIZE, 106, Short.MAX_VALUE)
                            .addComponent(cusnme))
                        .addGap(18, 18, 18)
                        .addComponent(jLabel3)
                        .addGap(18, 18, 18)
                        .addComponent(cusnme1)
                        .addGap(8, 8, 8))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(102, 102, 102)
                        .addComponent(addcus)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(seacus)
                        .addGap(66, 66, 66))))
            .addGroup(layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addComponent(newcus)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 170, Short.MAX_VALUE)
                .addComponent(exscus)
                .addGap(28, 28, 28))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(51, 51, 51)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(newcus)
                    .addComponent(exscus))
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel3)
                        .addComponent(cusnme1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel1)
                        .addComponent(cusnme, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(cusnum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(73, 73, 73)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(addcus)
                    .addComponent(seacus))
                .addContainerGap(45, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cusnumActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cusnumActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cusnumActionPerformed

    private void addcusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addcusActionPerformed
        // TODO add your handling code here:
        cus_name = cusnme.getText();
        mob_num = cusnum.getText();
        try{
            String query="INSERT INTO Customer VALUES(?,?,?,?)";
                    pst=con.prepareStatement(query);
                    pst.setString(1,cus_name);
                    pst.setString(2,mob_num);
                    pst.setInt(3, 0);
                    pst.setDouble(4, 0);
                    pst.executeUpdate();
        }
        catch(Exception e)
        {
            
        }
        this.setVisible(false);
        jFrame1.setVisible(true);
        
    }//GEN-LAST:event_addcusActionPerformed

    private void cusnmeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cusnmeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cusnmeActionPerformed

    private void cusnme1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cusnme1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cusnme1ActionPerformed

    private void seacusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_seacusActionPerformed
        // TODO add your handling code here:
        cus_name1 = cusnme1.getText();
        this.setVisible(false);
        jFrame1.setVisible(true);
    }//GEN-LAST:event_seacusActionPerformed

    private void codebillActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_codebillActionPerformed
        // TODO add your handling code here:
        cuscodee = Integer.parseInt(getcode.getText());
        cusquann = Integer.parseInt(cusquan.getText());
        try{
            
        String querys = "Select * from sub where pro_code=?";
                    pst=con.prepareStatement(querys);
                    pst.setInt(1, cuscodee);
                    rs = pst.executeQuery();
                    while(rs.next())
                    {
                    String pro_name= rs.getString("pro_name");
                    double price = rs.getDouble("price");
                    int stock = rs.getInt("stock");
                    int sto_upd = stock - cusquann;
                    
                    tot=tot+(price*cusquann);
                    prcode1.setText(pro_name);
                    prcode2.setText(cusquann+"");
                    prcode.setText(tot+"");
                    tocus +=tot;

                    
                    String queryy = "INSERT INTO Bill VALUES(?,?,?,?,?)";
                    pst = con.prepareStatement(queryy);
                    pst.setInt(1,cuscodee);
                    pst.setString(2,pro_name);
                    pst.setDouble(3,price);
                    pst.setDouble(4,tot);
                    pst.setInt(5, cusquann);
                    pst.executeUpdate();
                    
                    String queryyy="Update sub set stock=? where pro_code=?";
                    pst=con.prepareStatement(queryyy);
                    pst.setInt(1, sto_upd);
                    pst.setInt(2, cuscodee);
                    pst.executeUpdate();
                    
                    
                    String queryyyy="Update Customer set No_of_pur=?, Bill_amount=? where Cust_name=?";
                    pst=con.prepareStatement(queryyyy);
                    pst.setInt(1,cnt);
                    pst.setDouble(2, tocus);
                    pst.setString(3, cus_name);
                    pst.executeUpdate();
                    

                    
                    }
                }
        catch(Exception e)
        {
            
        }
        getcode.setText("");
        cusquan.setText("");
        
        
        
    }//GEN-LAST:event_codebillActionPerformed

    private void getcodeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_getcodeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_getcodeActionPerformed

    private void backhomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backhomeActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        jFrame3.setVisible(true);
        totbiling.setText(tocus+"");
    }//GEN-LAST:event_backhomeActionPerformed

    private void homeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_homeActionPerformed
        // TODO add your handling code here:

        this.setVisible(false);

        Jsmbs ob = new Jsmbs();
        
        ob.setVisible(true);
    }//GEN-LAST:event_homeActionPerformed

    private void getcode1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_getcode1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_getcode1ActionPerformed

    private void codebill1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_codebill1ActionPerformed
        // TODO add your handling code here:
        cuscodee1 = Integer.parseInt(getcode1.getText());
        cusquann1 = Integer.parseInt(cusquan1.getText());
        try{
            
        String querys = "Select * from sub where pro_code=?";
                    pst=con.prepareStatement(querys);
                    pst.setInt(1, cuscodee1);
                    rs = pst.executeQuery();
                    while(rs.next())
                    {
                    String pro_name= rs.getString("pro_name");
                    double price = rs.getDouble("price");
                    int stock = rs.getInt("stock");
                    int sto_upd = stock - cusquann1;
                    tot1=0;
                    tot1=tot1+(price*cusquann1);
                    prcode1.setText(pro_name);
                    prcode2.setText(cusquann1+"");
                    prcode.setText(tot1+"");
                    tot_cus1+=tot1;

                    //System.out.println("");
                    //System.out.println(pro_name+"\t\t"+cusquann+"\t\t"+tot);
                    //pst.close();
                    String queryy = "INSERT INTO Bill VALUES(?,?,?,?,?)";
                    pst = con.prepareStatement(queryy);
                    pst.setInt(1,cuscodee1);
                    pst.setString(2,pro_name);
                    pst.setDouble(3,price);
                    pst.setDouble(4,tot1);
                    pst.setInt(5, cusquann1);
                    pst.executeUpdate();
                    
                    String queryyy="Update sub set stock=? where pro_code=?";
                    pst=con.prepareStatement(queryyy);
                    pst.setInt(1, sto_upd);
                    pst.setInt(2, cuscodee1);
                    pst.executeUpdate();
                    
                    
                    String ques="Update Customer set No_of_pur=?, Bill_amount=? where Cust_name=?";
                    pst=con.prepareStatement(ques);
                    pst.setInt(1,cnt);
                    pst.setDouble(2, tot_cus1);
                    pst.setString(3, cus_name1);
                    pst.executeUpdate();
                    }
        }catch(Exception e)
        {
            
        }
        getcode.setText("");
        cusquan.setText("");
        
        
                    
    }//GEN-LAST:event_codebill1ActionPerformed

    private void backhome1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backhome1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_backhome1ActionPerformed

    private void cusquan1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cusquan1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cusquan1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Billing.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Billing.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Billing.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Billing.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Billing().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addcus;
    private javax.swing.JButton backhome;
    private javax.swing.JButton backhome1;
    private javax.swing.JButton codebill;
    private javax.swing.JButton codebill1;
    private javax.swing.JTextField cusnme;
    private javax.swing.JTextField cusnme1;
    private javax.swing.JTextField cusnum;
    private javax.swing.JTextField cusquan;
    private javax.swing.JTextField cusquan1;
    private javax.swing.JRadioButton exscus;
    private javax.swing.JTextField getcode;
    private javax.swing.JTextField getcode1;
    private javax.swing.JButton home;
    private javax.swing.JFrame jFrame1;
    private javax.swing.JFrame jFrame2;
    private javax.swing.JFrame jFrame3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JRadioButton newcus;
    private javax.swing.JLabel prcode;
    private javax.swing.JLabel prcode1;
    private javax.swing.JLabel prcode2;
    private javax.swing.JLabel prcode3;
    private javax.swing.JLabel prcode4;
    private javax.swing.JLabel prcode5;
    private javax.swing.JButton seacus;
    private javax.swing.JLabel totbiling;
    // End of variables declaration//GEN-END:variables
}
