/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package smbs;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;

/**
 *
 * @author sriram
 */
public class Update extends javax.swing.JFrame {
    
    private Connection con;
    private Statement st;
    private PreparedStatement pst;
    private ResultSet rs;
    String pro_namee,pro_detaill;
    int pro_codee,stockk,min_stockk;
    double pricee;

    /** Creates new form Update */
    public Update() {
        try
        {
          Class.forName("com.mysql.jdbc.Driver");
          con = DriverManager.getConnection("jdbc:mysql://localhost:3306/Super?zeroDateTimeBehavior=convertToNull","root","");
          st = con.createStatement();
        }
        catch(Exception ex){
            System.out.println("Error : "+ex);
        }
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jFrame1 = new javax.swing.JFrame();
        jLabel1 = new javax.swing.JLabel();
        pro_name = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        pro_code = new javax.swing.JTextField();
        cdeupd = new javax.swing.JButton();
        jFrame2 = new javax.swing.JFrame();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        pro_name2 = new javax.swing.JTextField();
        pro_cod2 = new javax.swing.JTextField();
        nmeupd = new javax.swing.JButton();
        jFrame3 = new javax.swing.JFrame();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        price = new javax.swing.JTextField();
        pro_cod3 = new javax.swing.JTextField();
        priupd = new javax.swing.JButton();
        jFrame4 = new javax.swing.JFrame();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        stock = new javax.swing.JTextField();
        pro_cod4 = new javax.swing.JTextField();
        stcupd = new javax.swing.JButton();
        jFrame5 = new javax.swing.JFrame();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        pro_detail = new javax.swing.JTextField();
        pro_cod5 = new javax.swing.JTextField();
        detupd = new javax.swing.JButton();
        jFrame6 = new javax.swing.JFrame();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        min_stock = new javax.swing.JTextField();
        pro_cod6 = new javax.swing.JTextField();
        minupd = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        procode = new javax.swing.JRadioButton();
        proname = new javax.swing.JRadioButton();
        pri = new javax.swing.JRadioButton();
        stck = new javax.swing.JRadioButton();
        jRadioButton5 = new javax.swing.JRadioButton();
        minstck = new javax.swing.JRadioButton();
        backk = new javax.swing.JButton();

        jFrame1.setMinimumSize(new java.awt.Dimension(100, 100));
        jFrame1.setSize(new java.awt.Dimension(350, 350));

        jLabel1.setText("Enter Product name :");

        jLabel2.setText("Enter new Product code :");

        cdeupd.setText("Update");
        cdeupd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cdeupdActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jFrame1Layout = new javax.swing.GroupLayout(jFrame1.getContentPane());
        jFrame1.getContentPane().setLayout(jFrame1Layout);
        jFrame1Layout.setHorizontalGroup(
            jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jFrame1Layout.createSequentialGroup()
                .addGroup(jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jFrame1Layout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addGroup(jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel1))
                        .addGap(45, 45, 45)
                        .addGroup(jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(pro_name, javax.swing.GroupLayout.DEFAULT_SIZE, 118, Short.MAX_VALUE)
                            .addComponent(pro_code)))
                    .addGroup(jFrame1Layout.createSequentialGroup()
                        .addGap(139, 139, 139)
                        .addComponent(cdeupd)))
                .addContainerGap(68, Short.MAX_VALUE))
        );
        jFrame1Layout.setVerticalGroup(
            jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jFrame1Layout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addGroup(jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(pro_name, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(36, 36, 36)
                .addGroup(jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(pro_code, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(56, 56, 56)
                .addComponent(cdeupd)
                .addContainerGap(81, Short.MAX_VALUE))
        );

        jFrame2.setSize(new java.awt.Dimension(350, 350));

        jLabel3.setText("Enter new Product name :");

        jLabel4.setText("Enter Product code :");

        nmeupd.setText("Update");
        nmeupd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nmeupdActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jFrame2Layout = new javax.swing.GroupLayout(jFrame2.getContentPane());
        jFrame2.getContentPane().setLayout(jFrame2Layout);
        jFrame2Layout.setHorizontalGroup(
            jFrame2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jFrame2Layout.createSequentialGroup()
                .addGroup(jFrame2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jFrame2Layout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addGroup(jFrame2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4))
                        .addGap(45, 45, 45)
                        .addGroup(jFrame2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(pro_cod2, javax.swing.GroupLayout.DEFAULT_SIZE, 118, Short.MAX_VALUE)
                            .addComponent(pro_name2)))
                    .addGroup(jFrame2Layout.createSequentialGroup()
                        .addGap(139, 139, 139)
                        .addComponent(nmeupd)))
                .addContainerGap(64, Short.MAX_VALUE))
        );
        jFrame2Layout.setVerticalGroup(
            jFrame2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jFrame2Layout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addGroup(jFrame2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(pro_cod2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(36, 36, 36)
                .addGroup(jFrame2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(pro_name2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(56, 56, 56)
                .addComponent(nmeupd)
                .addContainerGap(81, Short.MAX_VALUE))
        );

        jFrame3.setSize(new java.awt.Dimension(350, 350));

        jLabel5.setText("Enter new Product price :");

        jLabel6.setText("Enter Product code:");

        priupd.setText("Update");
        priupd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                priupdActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jFrame3Layout = new javax.swing.GroupLayout(jFrame3.getContentPane());
        jFrame3.getContentPane().setLayout(jFrame3Layout);
        jFrame3Layout.setHorizontalGroup(
            jFrame3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jFrame3Layout.createSequentialGroup()
                .addGroup(jFrame3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jFrame3Layout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addGroup(jFrame3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6))
                        .addGap(45, 45, 45)
                        .addGroup(jFrame3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(pro_cod3, javax.swing.GroupLayout.DEFAULT_SIZE, 118, Short.MAX_VALUE)
                            .addComponent(price)))
                    .addGroup(jFrame3Layout.createSequentialGroup()
                        .addGap(139, 139, 139)
                        .addComponent(priupd)))
                .addContainerGap(67, Short.MAX_VALUE))
        );
        jFrame3Layout.setVerticalGroup(
            jFrame3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jFrame3Layout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addGroup(jFrame3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(pro_cod3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(36, 36, 36)
                .addGroup(jFrame3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(price, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(56, 56, 56)
                .addComponent(priupd)
                .addContainerGap(81, Short.MAX_VALUE))
        );

        jFrame4.setSize(new java.awt.Dimension(350, 350));

        jLabel7.setText("Enter new Product stock :");

        jLabel8.setText("Enter Product code :");

        stcupd.setText("Update");
        stcupd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                stcupdActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jFrame4Layout = new javax.swing.GroupLayout(jFrame4.getContentPane());
        jFrame4.getContentPane().setLayout(jFrame4Layout);
        jFrame4Layout.setHorizontalGroup(
            jFrame4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jFrame4Layout.createSequentialGroup()
                .addGroup(jFrame4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jFrame4Layout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addGroup(jFrame4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel7)
                            .addComponent(jLabel8))
                        .addGap(45, 45, 45)
                        .addGroup(jFrame4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(pro_cod4, javax.swing.GroupLayout.DEFAULT_SIZE, 118, Short.MAX_VALUE)
                            .addComponent(stock)))
                    .addGroup(jFrame4Layout.createSequentialGroup()
                        .addGap(139, 139, 139)
                        .addComponent(stcupd)))
                .addContainerGap(63, Short.MAX_VALUE))
        );
        jFrame4Layout.setVerticalGroup(
            jFrame4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jFrame4Layout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addGroup(jFrame4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(pro_cod4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(36, 36, 36)
                .addGroup(jFrame4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(stock, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(56, 56, 56)
                .addComponent(stcupd)
                .addContainerGap(81, Short.MAX_VALUE))
        );

        jFrame5.setSize(new java.awt.Dimension(350, 350));

        jLabel9.setText("Enter new Product details :");

        jLabel10.setText("Enter Product code :");

        detupd.setText("Update");
        detupd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                detupdActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jFrame5Layout = new javax.swing.GroupLayout(jFrame5.getContentPane());
        jFrame5.getContentPane().setLayout(jFrame5Layout);
        jFrame5Layout.setHorizontalGroup(
            jFrame5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jFrame5Layout.createSequentialGroup()
                .addGroup(jFrame5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jFrame5Layout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addGroup(jFrame5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel9)
                            .addComponent(jLabel10))
                        .addGap(45, 45, 45)
                        .addGroup(jFrame5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(pro_cod5, javax.swing.GroupLayout.DEFAULT_SIZE, 118, Short.MAX_VALUE)
                            .addComponent(pro_detail)))
                    .addGroup(jFrame5Layout.createSequentialGroup()
                        .addGap(139, 139, 139)
                        .addComponent(detupd)))
                .addContainerGap(56, Short.MAX_VALUE))
        );
        jFrame5Layout.setVerticalGroup(
            jFrame5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jFrame5Layout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addGroup(jFrame5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(pro_cod5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(36, 36, 36)
                .addGroup(jFrame5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(pro_detail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(56, 56, 56)
                .addComponent(detupd)
                .addContainerGap(81, Short.MAX_VALUE))
        );

        jFrame6.setSize(new java.awt.Dimension(350, 350));

        jLabel11.setText("Enter new Min Stock :");

        jLabel12.setText("Enter Product code :");

        minupd.setText("Update");
        minupd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                minupdActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jFrame6Layout = new javax.swing.GroupLayout(jFrame6.getContentPane());
        jFrame6.getContentPane().setLayout(jFrame6Layout);
        jFrame6Layout.setHorizontalGroup(
            jFrame6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jFrame6Layout.createSequentialGroup()
                .addGroup(jFrame6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jFrame6Layout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addGroup(jFrame6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel11)
                            .addComponent(jLabel12))
                        .addGap(45, 45, 45)
                        .addGroup(jFrame6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(pro_cod6, javax.swing.GroupLayout.DEFAULT_SIZE, 118, Short.MAX_VALUE)
                            .addComponent(min_stock)))
                    .addGroup(jFrame6Layout.createSequentialGroup()
                        .addGap(139, 139, 139)
                        .addComponent(minupd)))
                .addContainerGap(88, Short.MAX_VALUE))
        );
        jFrame6Layout.setVerticalGroup(
            jFrame6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jFrame6Layout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addGroup(jFrame6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(pro_cod6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(36, 36, 36)
                .addGroup(jFrame6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(min_stock, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(56, 56, 56)
                .addComponent(minupd)
                .addContainerGap(81, Short.MAX_VALUE))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        buttonGroup1.add(procode);
        procode.setText("Product code");
        procode.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                procodeActionPerformed(evt);
            }
        });

        buttonGroup1.add(proname);
        proname.setText("Product name");
        proname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pronameActionPerformed(evt);
            }
        });

        buttonGroup1.add(pri);
        pri.setText("Price");
        pri.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                priActionPerformed(evt);
            }
        });

        buttonGroup1.add(stck);
        stck.setText("Stock");
        stck.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                stckActionPerformed(evt);
            }
        });

        buttonGroup1.add(jRadioButton5);
        jRadioButton5.setText("Product Detail");
        jRadioButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton5ActionPerformed(evt);
            }
        });

        buttonGroup1.add(minstck);
        minstck.setText("Minimum Stock");
        minstck.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                minstckActionPerformed(evt);
            }
        });

        backk.setText("Back");
        backk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backkActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(minstck)
                    .addComponent(jRadioButton5)
                    .addComponent(stck)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(procode)
                        .addComponent(pri)
                        .addComponent(proname)))
                .addContainerGap(250, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(backk)
                .addGap(80, 80, 80))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(procode)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(proname)
                .addGap(18, 18, 18)
                .addComponent(pri)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(stck)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jRadioButton5)
                .addGap(18, 18, 18)
                .addComponent(minstck)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(backk)
                .addContainerGap(20, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void procodeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_procodeActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        jFrame1.setVisible(true);
    }//GEN-LAST:event_procodeActionPerformed

    private void pronameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pronameActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        jFrame2.setVisible(true);
    }//GEN-LAST:event_pronameActionPerformed

    private void priActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_priActionPerformed
        // TODOx add your handling code here:
        this.setVisible(false);
        jFrame3.setVisible(true);
    }//GEN-LAST:event_priActionPerformed

    private void stckActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_stckActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        jFrame4.setVisible(true);
    }//GEN-LAST:event_stckActionPerformed

    private void jRadioButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton5ActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        jFrame5.setVisible(true);
    }//GEN-LAST:event_jRadioButton5ActionPerformed

    private void minstckActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_minstckActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        jFrame6.setVisible(true);
    }//GEN-LAST:event_minstckActionPerformed

    private void cdeupdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cdeupdActionPerformed
        // TODO add your handling code here:
        this.setVisible(true);
        pro_namee = pro_name.getText();
        pro_codee = Integer.parseInt(pro_code.getText());
        try{
            String query = "Update Sub set pro_code=? where pro_name=?";
        
         pst=con.prepareStatement(query);
         pst.setInt(1,pro_codee);
         pst.setString(2,pro_namee);
         int suc;
         suc=pst.executeUpdate();
        }catch(Exception e)
        {
            
        }
        
    }//GEN-LAST:event_cdeupdActionPerformed

    private void nmeupdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nmeupdActionPerformed
        // TODO add your handling code here:
        this.setVisible(true);
        pro_namee = pro_name2.getText();
        pro_codee = Integer.parseInt(pro_cod2.getText());
        try{
            String query = "Update Sub set pro_name=? where pro_code=?";
                    pst=con.prepareStatement(query);
                    pst.setInt(2,pro_codee);
                    pst.setString(1,pro_namee);
                    int suc;
                    suc=pst.executeUpdate();
        }catch(Exception e)
        {
            
        }
    }//GEN-LAST:event_nmeupdActionPerformed

    private void priupdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_priupdActionPerformed
        // TODO add your handling code here:
        this.setVisible(true);
        pricee = Double.parseDouble(price.getText());
        pro_codee = Integer.parseInt(pro_cod3.getText());
        try{
            String query = "Update Sub set price=? where pro_code=?";
                    pst=con.prepareStatement(query);
                    pst.setInt(2,pro_codee);
                    pst.setDouble(1,pricee);
                    int suc;
                    suc=pst.executeUpdate();
        }catch(Exception e)
        {
            
        }
        
    }//GEN-LAST:event_priupdActionPerformed

    private void stcupdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_stcupdActionPerformed
        // TODO add your handling code here:
        this.setVisible(true);
        stockk = Integer.parseInt(stock.getText());
        pro_codee = Integer.parseInt(pro_cod4.getText());
        try{
             String query = "Update Sub set stock=? where pro_code=?";
                    pst=con.prepareStatement(query);
                    pst.setInt(2,pro_codee);
                    pst.setInt(1,stockk);
                    int suc;
                    suc=pst.executeUpdate();
        }catch(Exception e)
        {
            
        }
    }//GEN-LAST:event_stcupdActionPerformed

    private void detupdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_detupdActionPerformed
        // TODO add your handling code here:
        this.setVisible(true);
        pro_detaill = pro_detail.getText();
        pro_codee = Integer.parseInt(pro_cod5.getText());
        try{
            String query = "Update Sub set prod_deal=? where pro_code=?";
                    pst=con.prepareStatement(query);
                    pst.setInt(2,pro_codee);
                    pst.setString(1,pro_detaill);
                    int suc;
                    suc=pst.executeUpdate();
        }catch(Exception e)
        {
            
        }
    }//GEN-LAST:event_detupdActionPerformed

    private void minupdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_minupdActionPerformed
        // TODO add your handling code here:
        this.setVisible(true);
        min_stockk = Integer.parseInt(min_stock.getText());
        pro_codee = Integer.parseInt(pro_cod6.getText());
        try{
             String query = "Update Sub set stock=? where pro_code=?";
                    pst=con.prepareStatement(query);
                    pst.setInt(2,pro_codee);
                    pst.setInt(1,min_stockk);
                    int suc;
                    suc=pst.executeUpdate();
        }catch(Exception e)
        {
            
        }
    }//GEN-LAST:event_minupdActionPerformed

    private void backkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backkActionPerformed
        // TODO add your handling code here:
        Jsmbs ob= new Jsmbs();
        this.setVisible(false);
        ob.setVisible(true);
    }//GEN-LAST:event_backkActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Update.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Update.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Update.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Update.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Update().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backk;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton cdeupd;
    private javax.swing.JButton detupd;
    private javax.swing.JFrame jFrame1;
    private javax.swing.JFrame jFrame2;
    private javax.swing.JFrame jFrame3;
    private javax.swing.JFrame jFrame4;
    private javax.swing.JFrame jFrame5;
    private javax.swing.JFrame jFrame6;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JRadioButton jRadioButton5;
    private javax.swing.JTextField min_stock;
    private javax.swing.JRadioButton minstck;
    private javax.swing.JButton minupd;
    private javax.swing.JButton nmeupd;
    private javax.swing.JRadioButton pri;
    private javax.swing.JTextField price;
    private javax.swing.JButton priupd;
    private javax.swing.JTextField pro_cod2;
    private javax.swing.JTextField pro_cod3;
    private javax.swing.JTextField pro_cod4;
    private javax.swing.JTextField pro_cod5;
    private javax.swing.JTextField pro_cod6;
    private javax.swing.JTextField pro_code;
    private javax.swing.JTextField pro_detail;
    private javax.swing.JTextField pro_name;
    private javax.swing.JTextField pro_name2;
    private javax.swing.JRadioButton procode;
    private javax.swing.JRadioButton proname;
    private javax.swing.JRadioButton stck;
    private javax.swing.JButton stcupd;
    private javax.swing.JTextField stock;
    // End of variables declaration//GEN-END:variables

}
